/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.factorysim;

public class App {
  public static void main(String[] args) {
  }
  public String getGreeting() {
    return "Hello world";
  }
}
