/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.factorysim;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testAppHasAGreeting() {
        String greeting = new App().getGreeting();
        assertEquals("Hello world", greeting);
    }

}
