/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.factorysim;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.parallel.ResourceAccessMode;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.junit.jupiter.api.parallel.Resources;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

class AppTest {

    @Test
    @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
    void test_main()throws IOException{
        ByteArrayOutputStream bytes=new ByteArrayOutputStream();
        PrintStream out=new PrintStream(bytes,true);

        InputStream input = getClass().getClassLoader().getResourceAsStream("inputs/input1.txt");
        assertNotNull(input);

        InputStream expectedStream = getClass().getClassLoader().getResourceAsStream("outputs/output1.txt");
        assertNotNull(expectedStream);
        InputStream oldIn = System.in;
        PrintStream oldOut = System.out;

        try {
            System.setIn(input);
            System.setOut(out);
            String filePath = "src/test/resources/inputs/doors1.json";
            String[] args = {filePath};
            App.main(args);
//            App.actualMain(filePath, new BufferedReader(new InputStreamReader(System.in)));
        }
        finally {
            //replace back
            System.setIn(oldIn);
            System.setOut(oldOut);
        }
        //output.txt as expected
        String expected = new String(expectedStream.readAllBytes()).replace("\r\n", "\n");

        //actual output
        String actual = bytes.toString().replace("\r\n", "\n");
        assertEquals(expected, actual);
        expectedStream.close();
        input.close();

    }
    
    @Test
    void test_createTempFile_and_deleteTempFile() throws IOException {
        String testContent = "test";
        File tempFile = App.createTempFile("test", ".json", testContent);
        assertTrue(tempFile.exists());
        String fileContent = new String(Files.readAllBytes(tempFile.toPath()));
        assertEquals(testContent, fileContent);
        App.deleteTempFile(tempFile);
        assertFalse(tempFile.exists());
    }
    
    @Test
    void test_deleteTempFile_null() {
        assertDoesNotThrow(() -> App.deleteTempFile(null));
    }
    
    @Test
    void test_deleteTempFile_nonexistent() {
        File nonExistentFile = new File("non_existent_file.txt");
        assertDoesNotThrow(() -> App.deleteTempFile(nonExistentFile));
    }
}
